from ai_pr_review.github.comment import COMMENT_DISCLAIMER, build_issue_comment_body


def test_build_issue_comment_body_includes_disclaimer_and_report():
    markdown_report = (
        "# AI Review Report\n\n"
        "## PR Summary\n\n"
        "This PR adds coupon validation.\n"
    )

    comment_body = build_issue_comment_body(markdown_report)

    assert comment_body.startswith(COMMENT_DISCLAIMER)
    assert "This review was generated by AI PR Review Assistant." in comment_body
    assert "Please verify suggestions before applying changes." in comment_body
    assert "# AI Review Report" in comment_body
    assert "This PR adds coupon validation." in comment_body


def test_build_issue_comment_body_does_not_publish_to_github(monkeypatch):
    def fail_if_called(*args, **kwargs):
        raise AssertionError("GitHub API should not be called")

    monkeypatch.setattr("ai_pr_review.github.client.GitHubClient._get", fail_if_called)

    comment_body = build_issue_comment_body("## AI Summary\nNo issues found.")

    assert "## AI Summary" in comment_body


def test_build_issue_comment_body_handles_empty_report():
    comment_body = build_issue_comment_body("  \n")

    assert comment_body == COMMENT_DISCLAIMER
