COMMENT_DISCLAIMER = (
    "This review was generated by AI PR Review Assistant.\n"
    "Please verify suggestions before applying changes."
)


def build_issue_comment_body(markdown_report: str) -> str:
    report = markdown_report.strip()
    if not report:
        return COMMENT_DISCLAIMER
    return f"{COMMENT_DISCLAIMER}\n\n{report}"
